project:
  type: website

# execute:
#   freeze: auto

website:
  title: "Intro to Shiny for Python / Conf(2024)"
  announcement: 
    icon: info-circle
    dismissable: true
    content: "**Alert** - this site is under active construction"
    type: warning
    position: below-navbar
  navbar:
    logo: https://d33wubrfki0l68.cloudfront.net/71003073848110093780ea9a1c721439ad6b64f3/655ba/shiny-for-python.svg
    search: true
    left:
      - text: "Home"
        file: docs/index.qmd
      - text: Pre-requisites
        file: docs/pre-requisites.qmd

      - text: "Course material"
        file: docs/course.qmd

    tools: 
      - icon: github
        href: https://github.com/posit-conf-2024/intro-to-shiny-for-python
      - icon: discord
        href: https://discord.gg/AQVJzG2bnN

  sidebar:
    - title: "Course material"
      collapse-level: 4
      contents:
        - docs/course.qmd
        - section: "Hallo, Shiny express!"
          contents:      
            - href: docs/shiny-express.qmd
              text: Slides
            - section: "Exercises"
              contents: 
              - docs/exercises/express-01-hello-world/express-01-hello-world.qmd
              - docs/exercises/express-02-debug/express-02-debug.qmd
              - docs/exercises/express-03-filter/express-03-filter.qmd
              - docs/exercises/express-04-plot/express-04-plot.qmd
            - section: "Still to move"
              contents: 
              - docs/exercises/express-12-basic-ui.qmd
              - docs/exercises/express-13-reactivity.qmd
              - docs/exercises/express-14-dynamic-ui.qmd
              - docs/exercises/express-15-reactive-effect.qmd

        - section: "Reactivity"
          contents:
            - href: docs/test-slides.qmd
              text: Test
            - href: docs/reactivity.qmd
              text: Slides
            - section: "Exercises"
              contents: 
              - docs/exercises/express-05-reactive-effect/index.qmd
              - docs/exercises/6-reactive-event.qmd
              - docs/exercises/7-reactive-effects.qmd

        - section: "UI Customization"
          contents:
            - href: docs/ui-customization.qmd
              text: Slides
            - section: "Exercises"
              contents: 
              - docs/exercises/8-navsets.qmd
              - docs/exercises/9-cards.qmd
              - docs/exercises/10-layout.qmd
              - docs/exercises/11-value-boxes.qmd
              - docs/exercises/12-dynamic-ui.qmd
        - section: "Best practices"
          contents:
            - href: docs/best-practices.qmd
              text: Slides
            - section: "Exercises"
              contents: 
              - docs/exercises/13-ui-functions.qmd
              - docs/exercises/14-extract-functions.qmd

filters:
  - shinylive

format:
  html:
    theme: materia
    css: styles.css
    toc: true



